# Generated by Django 5.2.5 on 2025-08-13 01:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_approved_at_customuser_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0', max_length=128, region='EG', unique=True),
        ),
    ]
